services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: productos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  db2:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: usuarios
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    restart: always

  db3:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: auth
    ports:
      - "5434:5432"
    volumes:
      - postgres_data3:/var/lib/postgresql/data
    restart: always

  users:
    build: ./USERS
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db2:5432/usuarios
    depends_on:
      - db2
    restart: always

  productos:
    build: ./PRODUCTS
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/productos
    depends_on:
      - db
    restart: always

  auth:
    build: ./AUTH
    ports:
      - "5002:5002"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db2:5432/usuarios
    depends_on:
      - db2
    restart: always

  google_auth:
    build: ./GOOGLE_AUTH
    ports:
      - "5003:5003"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db3:5432/auth
    depends_on:
      - db3
    restart: always

volumes:
  postgres_data:
  postgres_data2:
  postgres_data3:
